### ISSUE TITLE
ptpy.ptp.PTPError: No USB PTP device found.

### ISSUE THREAD

**Issue by ntableman** [akabe/sigma-ptpy#8]
I have a Sigma fp and am trying to use your code on my Mac M1/Big Sur, but I keep getting ptpy.ptp.PTPError: No USB PTP device found and cannot figure out where to maybe look to see why ptpy isnt finding the cam. I know it is attached because in the system info it is listed.

Any ideas? Also what os/system are you using...maybe I just use Rasp Pi next.

**Comment by akabe** [comment]
I think it is a problem of ptpy, not this program, but I have no idea to solve.
